# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      branch:
        type: string
        required: true

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - name: Run CI
        run: npm ci
      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "hi@sihuiliang.com" 
      - name: Add suffix to version on PR prerelease
        if: inputs.branch != 'main' && inputs.branch != 'master'
        run: |
          BRANCH_NAME=${{ inputs.branch }}
          COMMIT_HASH=$(git rev-parse --short HEAD)
          npm version prerelease --preid=${BRANCH_NAME}-${COMMIT_HASH}
          echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" > ~/.npmrc
          echo "---------------- config ----------------"
          npm config list
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Run semantic-release on main or master
        if: inputs.branch == 'main' || inputs.branch == 'master'
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" > ~/.npmrc
          echo "---------------- config ----------------"
          npm config list
          npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
