# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      branch:
        type: string
        required: true

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - name: Run CI
        run: npm ci
      - name: Set user
        run: |
          git config --local user.email $(git log -1 --pretty=format:%an)
          git config --local user.name ${GITHUB_ACTOR}
      - name: Add suffix to version if not on main or master
        if: inputs.branch != 'main' && inputs.branch != 'master'
        run: |
          BRANCH_NAME=${{ inputs.branch }}
          COMMIT_HASH=$(git rev-parse --short HEAD)
          npm version prerelease --preid=${BRANCH_NAME}-${COMMIT_HASH}
          npm publish
      - name: Run semantic-release
        if: inputs.branch == 'main' || inputs.branch == 'master'
        run: |
          npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
